In [1]:
import numpy as np

In [6]:
escalar = 5.678
vector = np.array([3,4,5,6])
matriz = np.array([[1,2], [3,4],[5,6]])
tensor = np.array([
                   [[1,2,3,30],[4,5,6,31], [7,8,9,32]],
                   [[11,12,13,33], [14,15,16,34], [17,18,19,35]],
                   [[21,21,23,36],[24,25,26,37], [27,28,29, 38]],
])

In [7]:
escalat_t = escalar.T

AttributeError: ignored

In [8]:
vector_t = vector.T
print(vector_t)

[3 4 5 6]


In [10]:
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [11]:
print(matriz_t.shape)

(2, 3)


In [12]:
print(matriz.shape)

(3, 2)


In [13]:
# Para los tensores la transposicione es una generalizacion.
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 21]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [14]:
print(tensor)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 21 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


In [16]:
# Si aplicas la transpuesta a estas matrices debes recobrar la matriz original
matriz_t_t = matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
# La suma de matrices se da si y solo si las matrices tienen las mismas dimensiones
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A + B

In [20]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
print(B)

[[6 5]
 [4 3]
 [2 1]]


In [23]:
print(C)

[[7 7]
 [7 7]
 [7 7]]


In [25]:
# Tambien podemos sumar un escalar a una matriz afectando todos sus elementos
D = matriz + escalar
print(D)

[[ 6.678  7.678]
 [ 8.678  9.678]
 [10.678 11.678]]


In [26]:
# Reto sumar a una matriz su transpuesta
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [27]:
matriz_t = matriz.T

In [28]:
F = matriz + matriz_t

In [30]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print(matriz_t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [29]:
print(F)

[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
