In [1]:
import numpy as np

In [2]:
escalar = 5.678
vector = np.array([3,4,5])
matriz = np.array([[1,2], [3,4],[5,6]])

In [3]:
A = matriz + vector

ValueError: ignored

In [11]:
# Utilizo la transpuesta de la matriz
A = matriz.T + vector

In [7]:
print(matriz.T)

[[1 3 5]
 [2 4 6]]


In [8]:
print(vector)

[3 4 5]


In [9]:
# Python hace broadcasting internamente repitiendo el vector como segunda fila para ajustarse a la matriz

In [10]:
print(A)

[[ 4  7 10]
 [ 5  8 11]]
