In [1]:
import numpy as np

In [2]:
escalar = 5.678
vector = np.array([2,3])
matriz = np.array([[1,2], [3,4],[5,6]])

In [ ]:
A = matriz * vector

In [3]:
# producto punto
B = matriz.dot(vector)
print(B)

[ 8 18 28]


In [ ]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(vector)

[2 3]


In [ ]:
# Utilizando broadcasting obtuvimos el resultado
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


## Producto interno o producto punto (.dot)

Realizamos la siguiente operacion

![](https://matematicasmodernas.com/wp-content/uploads/2014/04/pp.jpeg)

In [ ]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(vector)

[2 3]


In [ ]:
# Operacion manual
print(np.array([(1*2 + 2*3), (3*2 + 3*4), (5*2 + 6*3)]))

[ 8 18 28]


In [ ]:
# Operacion python
print(B)

[ 8 18 28]


### Forma dos de producto interno (punto)

In [ ]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)

In [ ]:
print(B)

[ 8 18 28]


In [ ]:
print(C)

[ 8 18 28]


### Ejercicio vector por matriz

In [ ]:
D = np.dot(vector, matriz)

ValueError: ignored

In [ ]:
F = vector.dot(matriz)

ValueError: ignored

In [ ]:
y = 7*x+2 y = 3*x+5

In [7]:
A = np.array([[7,-1], [3, -1]])
print(A)

[[ 7 -1]
 [ 3 -1]]


In [8]:
b = np.array([[-2], [-5]])
print(b)

[[-2]
 [-5]]


In [9]:
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 0.25 -0.25]
 [ 0.75 -1.75]]


In [10]:
x = inversa_A.dot(b)
print(x)

[[0.75]
 [7.25]]
