In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
print(f'La matriz A es de la forma : {A.shape}')

La matriz A es de la forma : (4, 3)


In [4]:
print(f'La matriz B es de la forma : {B.shape}')

La matriz B es de la forma : (3, 2)


(4, **3**) y (3, 2) son compatibles con la operacion

![](https://matematicasmodernas.com/wp-content/uploads/2014/04/pp.jpeg)



In [5]:
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
C = A.dot(B)
print(C)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]]


In [ ]:
B.dot(A)

ValueError: ignored