In [1]:
import numpy as np

In [3]:
A = np.array([[2,3], [5,7], [11,13]])
B = np.array([[1,3], [2,1]])

In [4]:
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [5]:
print(B)

[[1 3]
 [2 1]]


In [8]:
AB_t = A.dot(B).T
print(AB_t)

[[ 8 19 37]
 [ 9 22 46]]


In [9]:
B_tA_t = B.T.dot(A.T)

In [10]:
print(B_tA_t == AB_t)

[[ True  True  True]
 [ True  True  True]]
