In [3]:
import numpy as np

In [5]:
vector = np.array([1,2,3,4,5])

matriz1 = np.diag(vector)

print(matriz1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [7]:
print(matriz1[0:4,0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [8]:
print(matriz1[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [15]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [16]:
v1 = np.array([[1,1,1,1]])

print(v1)

print(A.dot(v1.T))

[[1 1 1 1]]
[[2]
 [3]
 [4]
 [5]]


### Matriz inversa

In [17]:
# Obtenemos la inversa dividiendo entre los elementos de la diagonal
# de la matriz A
A_inv = np.diag([1/2, 1/3, 1/4, 1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [18]:
identidad = A.dot(A_inv)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


### Matriz simetrica

In [20]:
print(A.T)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [21]:
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [23]:
simetrica = np.array([[1,2,3],
                     [2,-1,7],
                     [3,7,11]])

print(simetrica)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [24]:
print(simetrica.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
