In [1]:
import numpy as np

In [4]:
matriz = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1],
                   ])

print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
# Comprobacion v1 ortogonal v2
print(matriz[:,0].dot(matriz[:,1]))

0


In [7]:
# Comprobacion v1 ortogonal v3
print(matriz[:,0].dot(matriz[:,2]))

0


In [8]:
# Comprobacion v2 ortogonal v3
print(matriz[:,1].dot(matriz[:,2]))

0


In [13]:
# Comprobar las filas son ortonormales
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


In [15]:
# Comprobar las columnas son ortogonales
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


In [16]:
# Comprobar las columnas son ortonormales
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


Las matrices son todas ortogonales con vectores ortonormales, no existe la definicion de matriz ortonormal

In [20]:
#utilizando una matriz de rotacion. 

A = np.array([[np.cos(100), -np.sin(100)],
             [np.sin(100), np.cos(100)]])

print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [22]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))


0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [23]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


In [25]:
A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

[[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]
[[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


Esta es la matriz identidad, la maquina toma el e-18 como si fuera un numero cercano a cero

In [26]:
print(1/A_t.dot(A))

[[ 1.00000000e+00 -1.25980837e+17]
 [-1.25980837e+17  1.00000000e+00]]


AL hacer esto el numero cercano a cero se transforma en un numero muy grande, intentando calcular  una inversa. Debemos tener cuidado para no expandir nuestros errores.

In [ ]:
matriz = np.array([[7,-7,3],
                   [1,1,0],
                   [0,0,1],
                   ])

print(matriz)